version: 2.1

orbs:
  coveralls: coveralls/coveralls@1.0.6

aliases:
  - &restore-cache
    restore_cache:
      key: dependency-cache-{{ checksum "package.json" }}
  - &install-deps
    run:
      name: Install dependencies
      command: npm ci
  - &build-packages
    run:
      name: Build
      command: npm run build

jobs:
  build:
    working_directory: ~/nest
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Update NPM version
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm ci
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build
          command: npm run build

  integration_tests:
    working_directory: ~/nest
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - *restore-cache
      - *install-deps
      - run:
          name: Integration tests
          command: npm run test:integration

  coverage:
    working_directory: ~/nest
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - *restore-cache
      - *install-deps
      - run:
          name: Test coverage
          command: npm run test:cov
      - coveralls/upload:
          path_to_lcov: ./coverage/e2e/lcov.i

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - integration_tests:
          requires:
            - build
      - coverage:
          requires:
            - build
